### ISSUE TITLE
Android app freezes

### ISSUE THREAD

**Issue by petr166** [souvik-ghosh/react-native-create-thumbnail#8]
I'm trying to generate a thumbnail for a remote mp4 video. When calling `createThumbnail()` the app freezes and never recovers. This is the repeating log from Android Studio.

```
2020-03-06 11:25:01.702 15987-16013/com.egn.memberapp W/MediaHTTPConnection: readAt 8470170 / 32768 => java.net.ProtocolException
2020-03-06 11:25:04.706 15987-16013/com.egn.memberapp D/MediaHTTPConnection: setReadTimeout with 15000ms
2020-03-06 11:25:04.707 15987-16013/com.egn.memberapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-03-06 11:25:04.708 15987-16013/com.egn.memberapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-03-06 11:25:04.960 15987-16013/com.egn.memberapp I/MediaHTTPConnection: response code = 200
2020-03-06 11:25:05.064 15987-16241/com.egn.memberapp D/MediaHTTPConnection: setReadTimeout with 15000ms
2020-03-06 11:25:05.065 15987-16241/com.egn.memberapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-03-06 11:25:05.066 15987-16241/com.egn.memberapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-03-06 11:25:05.313 15987-16241/com.egn.memberapp I/MediaHTTPConnection: response code = 200
2020-03-06 11:25:05.314 15987-16241/com.egn.memberapp E/MediaHTTPConnection: java.net.ProtocolException
        at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:383)
        at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:414)
        at android.media.MediaHTTPConnection.native_readAt(Native Method)
        at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:403)
        at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:143)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-03-06 11:25:05.315 15987-16241/com.egn.memberapp W/MediaHTTPConnection: readAt 8470170 / 32768 => java.net.ProtocolException
2020-03-06 11:25:05.318 15987-16092/com.egn.memberapp E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
2020-03-06 11:25:05.328 15987-16091/com.egn.memberapp I/ReactNativeJS: 'TCL: VideoThumbnail -> err', [Error: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference]
```

I'm testing on a real device Samsung Note SM-N975F Android 10, and this is my system info:
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 814.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.2
      System Images: android-27 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

**Comment by VietQuoc** [comment]
Have the same issue.
App freezes when creating thumbnails on Android.
Work well on iOS.

**Comment by souvik-ghosh** [comment]
Seems like it failed to manipulate the video file, this can happen in case the file is not supported by the underlying android api. I think we should try to catch this exception so that the app doesn't crash.

**Comment by souvik-ghosh** [comment]
@petr166 @VietQuoc A few changes were made to the android api. Can you please test this with **v1.1.1**?
